ambiata/x

x-attoparsec/src/X/Data/Attoparsec/Text.hs
x-attoparsec/test/Test/X/Data/Attoparsec/Text.hs

@tmcgilchrist this can be useful but it's hard to find a good name for this function.

Added a method to transform a parsing function to a Parser

---

x-attoparsec/src/X/Data/Attoparsec/Text.hs
x-attoparsec/test/Test/X/Data/Attoparsec/Text.hs

@charleso @domdere this is what I really need.

Changed the `eitherText` function to be used in a monadic context

---

x-optparse/src/X/Options/Applicative.hs
x-optparse/x-optparse.cabal

Update to shiny new optsparse-applicative

---

x-aeson/x-aeson.cabal
x-attoparsec/x-attoparsec.cabal
x-conduit/x-conduit.cabal
x-either/x-either.cabal
x-eithert/x-eithert.cabal
x-exception/x-exception.cabal
x-htoml/x-htoml.cabal
x-optparse/x-optparse.cabal
x-templatehaskell/x-templatehaskell.cabal

Noticed that this was still on the old name for disorder when I did the EitherT change.
This also upgrades p to the latest.

Upgrade disorder -> ambiata-disorder

---

master.toml

/cc @nhibberd https://github.com/ambiata/ops/issues/70

Upgrade master runner to use ambiata-doc-test

---

framework/mafia
x-aeson/ambiata-x-aeson.cabal
x-attoparsec/ambiata-x-attoparsec.cabal
x-conduit/ambiata-x-conduit.cabal
x-either/ambiata-x-either.cabal
x-eithert/ambiata-x-eithert.cabal
x-exception/ambiata-x-exception.cabal
x-htoml/ambiata-x-htoml.cabal
x-optparse/ambiata-x-optparse.cabal
x-templatehaskell/ambiata-x-templatehaskell.cabal

Also upgrades mafia and QuickCheck

Widen bounds on time to >= 1.4 && < 1.6

---

x-templatehaskell/src/X/Language/Haskell/TH.hs

Export textExp, add dataExp

---

x-conduit/ambiata-x-conduit.cabal
x-conduit/src/X/Data/Conduit/Binary.hs
x-conduit/test/Test/X/Data/Conduit/Binary.hs

Add sepByByteBounded for bytestring conduits

---

x-exception/src/X/Control/Monad/Catch.hs

Add hushM combinator

---

x-optparse/src/X/Options/Applicative.hs

To be used in conjunction with ambiata/cabal-extras#62

Add dependency flag

---

x-conduit/ambiata-x-conduit.cabal
x-either/ambiata-x-either.cabal
x-eithert/ambiata-x-eithert.cabal
x-optparse/ambiata-x-optparse.cabal

Widen bounds on transformers

---

master.toml
x-bytestring/.ghci
x-bytestring/ambiata-x-bytestring.cabal
x-bytestring/mafia
x-bytestring/src/X/Data/ByteString/Unsafe.hs
x-bytestring/test/Test/X/Data/ByteString/Unsafe.hs
x-bytestring/test/test.hs

Some savage unsafe bytestring ops which I need in blizzard and had written once already in sardine.
/cc @amosr @tranma

x-bytestring - add unsafeSplits and unsafeSlice

---

boris-git.toml

borisborisborisborisborisborisborisborisborisboris

---

x-attoparsec/ambiata-x-attoparsec.cabal
x-attoparsec/src/X/Data/Attoparsec/ByteString.hs
x-attoparsec/test/Test/X/Data/Attoparsec/ByteString.hs
x-attoparsec/test/Test/X/Data/Attoparsec/Gen.hs
x-attoparsec/test/test.hs

Using this in a couple of codebases now, probably belongs here.

Add byte-specialized sepBy1

---

x-conduit/ambiata-x-conduit.lock-7.8.4

Lock to lifted-base-0.2.3.6 for GHC 7.8.4

---

x-vector/ambiata-x-vector.cabal

Add X.Data.Vector.Stream.Group to .cabal

---

boris-git.toml
boris.toml
framework/mafia
x-optparse/ambiata-x-optparse.lock-7.10.2
x-optparse/src/X/Options/Applicative.hs
x-optparse/test/Test/X/Options/Applicative.hs

! @charleso @jystic @thumphries @tmcgilchrist 
Ideal use case
```
main :: IO ()
main = do
cli "my-cli" buildInfoVersion dependencyInfo myThingParser $ \c -> 
case c of
DoThingA -> ...
DoThingB -> ...
main :: IO ()
main = do
daemon "my-daemon" buildInfoVersion dependencyInfo $ do
loop my-loop
```

Adding run combinators for cli and daemon

---

x-vector/src/X/Data/Vector/Grow.hs

Trivial (but useful) comment.
! @jystic

X.Data.Vector.Grow: Comment use of unsafeGrow

---

x-aeson/ambiata-x-aeson.cabal
x-aeson/ambiata-x-aeson.lock-7.10.2
x-aeson/src/X/Data/Aeson/TH.hs

Adding json quasi quoter

---

x-templatehaskell/src/X/Language/Haskell/TH/Syntax.hs

! @charleso 
/jury approved @charleso

x-th: add smart constructor for records

---

x-templatehaskell/src/X/Language/Haskell/TH/Syntax.hs

x-th: Add recConE

---

x-htoml/ambiata-x-htoml.cabal

! @thumphries @jystic 
We're hoping to use a more recent version of containers to get `Map.Merge`.
```
--- Diff for | 4.14 → 4.15.1 | ---
- Data.Map.Lens
· Control.Lens.Internal.Zoom
[+ Added] [- Removed] [× Modified] [· Unmodified]
```
/jury approved @jystic @nhibberd

Extend lens upper bounds

---

x-aeson/ambiata-x-aeson.cabal

! @nhibberd @tranma 
/jury approved @thumphries

Widen bounds on aeson

---

x-eithert/src/X/Control/Monad/Trans/Either.hs

I found myself doing `joinEitherT id . firstT f` all the time, so I went to add a thing. These combinators are all related though, so I thought it was time for a clean up so they have more obviously related names.
Fwiw, `bimapJoin id id == Control.Monad.Morph.squash`
! @nhibberd @tranma @thumphries 
/jury approved @nhibberd @thumphries

x-eithert: more consistent combinators for joining nested EitherTs

---

x-vector/ambiata-x-vector.cabal

0.12 has some handy stuff.
! @jystic
/jury approved @jystic

Bump vector upper bound

---

x-vector/ambiata-x-vector.cabal

Data.Vector.Fusion.Bundle was introduced in vector-0.11.0.0.
! @jystic

x-vector: correct lower bound for vector

---

x-conduit/ambiata-x-conduit.cabal
x-conduit/src/X/Data/Conduit/Either.hs
x-conduit/test/Test/X/Data/Conduit/Either.hs
x-conduit/test/test.hs

Conduit combinators for working with Conduits containing Either
values.
Code came from Jumbuck but need this functionality in Graft.
! @tmcgilchrist @jystic @nhibberd 
/jury approved @tmcgilchrist

Add module X.Data.Conduit.Either

---

x-vector/src/X/Data/Vector/Ref.hs

I keep finding that this API is so general I need type annotations, these specialisations for `newRef` should help.
! @tranma @nhibberd 
/jury approved @nhibberd @tranma

Add specialisations of newRef

---

x-conduit/src/X/Data/Conduit/Either.hs
x-conduit/test/Test/X/Data/Conduit/Either.hs

Need these for atavism.
! @tmcgilchrist 
/jury approved @tmcgilchrist

Add two new Conduit.Either functions

---

x-templatehaskell/ambiata-x-templatehaskell.cabal

Widen syb bounds.

---

x-conduit/src/X/Data/Conduit/Either.hs
x-conduit/test/Test/X/Data/Conduit/Either.hs

This was originally in Jumbuck but I need it in Gravel.
! @tmcgilchrist @olorin 
/jury approved @amosr @erikd-ambiata

Add groupRightsBy
