ambiata/x

- x-exception/src/X/Control/Monad/Catch.hs
Had to change `pure` to `return`, `<$>` to `liftM` to avoid adding redundant constraints.
> Generalise bracket from IO -> MonadMask m

- x-either/src/X/Control/Monad/Trans/Either.hs
I spent a bit of time staring at `joinErrors` yesterday night trying to grok what it was doing.
Breaking it down like this helped me understand it a bit better.
Not sure if this is a useful change, what do people think?
> Break joinErrors up in to simpler parts

- x-either/src/X/Control/Monad/Trans/Either.hs
- x-either/test/Test/X/Control/Monad/Trans/Either.hs
`joinErrors` is good but wanted to make the `hoist -> join` cycle a little more concise, i think they're going to appear consecutively often enough for us to consider it a concept.
@etorreborre 
--------
Reminder for myself:
TODO:
> reduceEitherT

- x-eithert/src/X/Control/Monad/Trans/Either.hs
Useful for creating `EitherT` without importing pattern synonym or `ExceptT`
> Adding newEitherT

- framework/mafia
- x-show/.ghci
- x-show/ambiata-x-show.cabal
- x-show/mafia
- x-show/src/X/Text/Show.hs
- x-show/test/Test/X/Text/Show.hs
- x-show/test/test.hs
This will show `newtype Foo = Foo { unFoo :: Int }` as `Foo 0` rather than `Foo { unFoo = 0 }` which can make understanding printouts with lots of newtypes a lot more pleasant, while still allowing you to paste the resulting output in to your editor or the repl.
To use it, you just derive your type from `Generic`, then instead of deriving `Show` as normal, you do it like this:
```hs
{-# LANGUAGE DeriveGeneric #-}
import           GHC.Generics (Generic)
import           X.Text.Show (gshowsPrec)
newtype Foo =
Foo {
unFoo :: Int
} deriving (Generic)
instance Show Foo where
showsPrec =
gshowsPrec
```
I wouldn't use this for all record types, just ones where the labels don't offer any useful additional context.
> Generic version of Show which doesn't contain record labels

- x-exception/src/X/Control/Monad/Catch.hs
This is possibly a bit controversial :)
The idea behind `Disaster` is that you sometimes have an error case which happens when some unknown exception is thrown and it should never really happen. Handling this means that your entire error type can't implement `Eq`, which is quite inconvenient.
The reason I went for saying that no two exceptions are the same is that I think this is the safest approach for something like this, an alternative might be comparing strings :worried: 
/cc  @nhibberd @markhibberd @charleso
> Add newtype Disaster wrapper for SomeException

- x-vector/.ghci
- x-vector/ambiata-x-vector.cabal
- x-vector/mafia
- x-vector/src/X/Data/Vector.hs
- x-vector/src/X/Data/Vector/Generic.hs
- x-vector/src/X/Data/Vector/Primitive.hs
- x-vector/src/X/Data/Vector/Storable.hs
- x-vector/src/X/Data/Vector/Unboxed.hs
- x-vector/test/Test/X/Data/Vector/Generic.hs
- x-vector/test/test.hs
This adds the project `x-vector` with support for `mapMaybe`, `imapMaybe`, `mapMaybeM`, `imapMaybeM`.
After this will do `transpose :: Vector (Vector a) -> Vector (Vector a)`
/cc @amosr @tranma @olorin @erikd-ambiata
> x-vector: mapMaybe, imapMaybe, mapMaybeM, imapMaybeM

- x-aeson/test/Test/X/Data/Aeson.hs
Aeson post 0.8 changes the error messages reported in each of these paths, so we now discard them.
Couldn't use `first (const ())` here as I didn't want to add a dependency on `bifunctor`.
I increased the number of tests because it only fails 1 in 5 with tests set to 100.
> Fix invalid 'as' <-> 'asWith' comparison

- x-vector/ambiata-x-vector.cabal
- x-vector/bench/bench.hs
- x-vector/src/X/Data/Vector.hs
- x-vector/src/X/Data/Vector/Generic.hs
- x-vector/src/X/Data/Vector/Primitive.hs
- x-vector/src/X/Data/Vector/Storable.hs
- x-vector/src/X/Data/Vector/Unboxed.hs
- x-vector/test/Test/X/Data/Vector/Generic.hs
This adds the `Data.List.transpose` function, but over vectors.
The main downside is that we pessimistically allocate the largest possible number of columns for each row and then trim it with `unsafeSlice` once we know how many columns that row will have. Not sure if there is a fast way we could determine the final layout up front, but this will only be sub-optimal in the case of jagged (non-rectangular) vectors.
/cc @amosr
> x-vector: add transpose for vectors

- x-attoparsec/ambiata-x-attoparsec.cabal
- x-attoparsec/src/X/Data/Attoparsec/ByteString/Ascii.hs
So I don't have to write these every time I write a ByteString
parser. Some of them are re-exported from attoparsec to make the
interface consistent; in each case the implementation is the fastest
I'm aware of.
> Add trivial ASCII predicates on Word8s

- x-bytestring/ambiata-x-bytestring.cabal
- x-bytestring/src/X/Data/ByteString/Char8.hs
- x-bytestring/test/Test/X/Data/ByteString/Char8.hs
- x-bytestring/test/test.hs
Using this in a couple of places now, so figured I should add it here. This is the fastest pure-Haskell implementation I know; it would probably be faster in C but I don't know how people feel about C in libraries like `x`.
> Add asciiToLower

- x-aeson/ambiata-x-aeson.cabal
- x-aeson/src/X/Data/Aeson.hs
These were mostly written by cofarrell for another project. I added `parseEitherFail` and `parseMaybeFail`, two functions you will find in some form in almost all our aeson code.
Note that aeson already depends on all these extra packages. Moving this code here prevents those aeson implementation details from leaking all over our projects. Not sure if the constraints are loose enough, however.
@charleso @nhibberd @jystic
> x-aeson: port a bunch of useful combinators

- x-attoparsec/ambiata-x-attoparsec.cabal
- x-attoparsec/src/X/Data/Attoparsec/ByteString.hs
- x-attoparsec/test/Test/X/Data/Attoparsec/ByteString.hs
- x-attoparsec/test/Test/X/Data/Attoparsec/Text.hs
Just like [X.Data.Attoparsec.Text](https://github.com/ambiata/x/blob/master/x-attoparsec/src/X/Data/Attoparsec/Text.hs#L3) does it.
Then if a project needs only `Data.Attoparsec.ByteString` it will not need to explicitly depend on locked `attoparsec` but can depend on `x-attoparsec` only.
/cc @olorin
> Export Data.Attoparsec.ByteString from X.Data.Attoparsec.ByteString

- x-vector/src/X/Data/Vector/Generic.hs
- x-vector/test/Test/X/Data/Vector/Generic.hs
This is the same as [X.Data.ByteString.unsafeSplits](https://github.com/ambiata/x/blob/805c90051e042efc7c1ea91f8761e4cb88e896c6/x-bytestring/src/X/Data/ByteString/Unsafe.hs#L18-L29) but for vectors.
/cc @amosr @tranma
> Add 'unsafeSplits' for generic vectors

- x-vector/ambiata-x-vector.cabal
- x-vector/src/X/Data/Vector/Grow.hs
- x-vector/src/X/Data/Vector/Ref.hs
- x-vector/test/Test/X/Data/Vector/Grow.hs
- x-vector/test/Test/X/Data/Vector/Ref.hs
This adds two modules `X.Data.Vector.Ref` and `X.Data.Vector.Grow`.
`Ref` is similar to an `IORef`, but doesn't have the overhead of thread safety. It's parameterised by the vector used to store the value, so it can be boxed, unboxed or storable.
`Grow` is a mutable vector that can have elements pushed on to the back of it, then frozen in to an immutable vector - it is parameterised in a similar way to `Ref`.
/cc @amosr @tranma @markhibberd @nhibberd @olorin
> x-vector: add growable vector, similar to a Java ArrayList

- x-vector/src/X/Data/Vector/Grow.hs
- x-vector/test/Test/X/Data/Vector/Grow.hs
The new `append` operation is equivalent to adding each of the elements of a vector one after another to the grow vector, as demonstrated by the property test.
/cc @tranma @amosr @olorin
> x-vector: support for efficient append to a grow vector

- x-eithert/src/X/Control/Monad/Trans/Either.hs
```hs
hoistEither :: Monad m => Either x a -> EitherT x m a
```
vs
```hs
hoistMaybe :: Monad m => x -> Maybe a -> EitherT x m a
```
Not sure if this is worth it? I've used it in two places, so I thought it may be useful here.
An alternative is `hoistEither . maybeToRight x` or `eitherTFromMaybe x . pure`
/cc @tranma @nhibberd @charleso
> Add 'hoistMaybe', similar to 'hoistEither' but for Maybe

- boris.toml
- x-file-embed/.ghci
- x-file-embed/ambiata-x-file-embed.cabal
- x-file-embed/mafia
- x-file-embed/master.toml
- x-file-embed/src/X/Data/FileEmbed.hs
- x-file-embed/test/Test/X/Data/FileEmbed.hs
- x-file-embed/test/example/foo.c
- x-file-embed/test/example/foo.h
- x-file-embed/test/test.hs
`embedWhen` is a version of `embedDir` that takes a predicate to filter the files which you want to embed.
I want to put this here because if I put it in icicle then I get random linker errors in `hdevtools` which seem like they are staging problems.
Wasn't sure on the naming, we have `x-templatehaskell` instead of `x-template-haskell`, so maybe this should be `x-fileembed`? :shrugs:
! @amosr @nhibberd
> x-file-embed

- x-vector/src/X/Data/Vector/Stream/Group.hs
- x-vector/test/Test/X/Data/Vector/Stream/Group.hs
I'm currently using `chunked` in blizzard to create zebra blocks, but I should actually use `grouped` so that entities do not span across blocks.
! @amosr @tranma
> x-vector: Add 'grouped' combinator for chunking but maintaining groups

- x-optparse/ambiata-x-optparse.cabal
- x-optparse/ambiata-x-optparse.lock-7.10.2
- x-optparse/src/X/Options/Applicative.hs
This allows the use of [commandGroup](http://hackage.haskell.org/package/optparse-applicative-0.13.0.0/docs/Options-Applicative-Builder.html#v:commandGroup) for grouping commands. 
! @nhibberd @charleso
> Widen bounds for optparse-applicative to include 0.13

- x-eithert/src/X/Control/Monad/Trans/Either.hs
- x-eithert/test/Test/X/Control/Monad/Trans/Either.hs
These are combinators for running a batch of Either expressions independently, folding the error messages together if any of them fail.
I have been pasting `foldEither` around the place quite a bit lately, and recently needed `foldEitherT`, so I thought they might be general enough to propose here.
You can generalise to Semigroup but that would require reimplementing `Errors`, which is a handy validation type we get for free from `transformers`.
! @jystic @erikd-ambiata
> Add sequenceEitherT

- boris.toml
- framework/master.toml
- x-eithert/src/X/Control/Monad/Trans/Either.hs
I want mafia to support the last 3 major ghc releases, so this adds builds for `x-eithert` and `x-optparse` to make sure we don't break compatibility.
I also upgraded the master runner to the new one which uses `mafia` on the `PATH` on the build bot, rather than the shell script.
! @erikd-ambiata @thumphries
> x-eithert support for GHC 7.8

- boris.toml
- x-templatehaskell/ambiata-x-templatehaskell.cabal
- x-templatehaskell/src/X/Language/Haskell/TH/Syntax.hs
Adds some shorthand for constructing Haskell98-ish TH syntax trees.
This is intended as a defense mechanism against upstream `template-haskell` churn. The idea is to provide a stable bare-minimum interface protected by CPP, and provide lenses to set/get the unstable fields.
Will provide some simple lenses (like where-clauses) in `X.Language.Haskell.TH.Lens` at some point. Since we don't need prisms or isos we can do this without dependencies.
! @jystic @charleso @amosr
> Add syntax shorthand to x-templatehaskell

- x-vector/src/X/Data/Vector.hs
- x-vector/src/X/Data/Vector/Generic.hs
- x-vector/src/X/Data/Vector/Primitive.hs
- x-vector/src/X/Data/Vector/Storable.hs
- x-vector/src/X/Data/Vector/Unboxed.hs
I was just reading this code and noticed `uncons` is doing more work than necessary, which bugged me because I use it all the time.
I also noticed there was no `INLINE` pragmas on the specialised version, so I've added them.
! @amosr @nhibberd 
/jury approved @amosr
> X.Data.Vector.Generic.uncons cleanup

- x-vector/src/X/Data/Vector/Cons.hs
I don't think this will make a difference, but it won't hurt.
> x-vector: imap/imapM pass 'f' directly

- x-optparse/ambiata-x-optparse.cabal
- x-optparse/ambiata-x-optparse.lock-7.10.2
?
! @HuwCampbell @jystic 
/jury approved @jystic
> Widen bounds for optparse-applicative to include 0.14
